### ISSUE TITLE
Fatal error: Uncaught Error: Class "SoapClient" not found

### ISSUE THREAD

**Issue by seal-82** [blacksenator/fbcontactconv#3]
After installing as described in the manual, I'm facing an issue when running "./fbcontactconv run":

`Fatal error: Uncaught Error: Class "SoapClient" not found in /volume2/web/fbcontactconv/vendor/blacksenator/fritzsoap/src/fritzsoap.php:117`

I'm running on PHP8.2.

Any hints/ideas where the issue comes from? According to phpinfo(); all necessary modules are enabled (especially "Soap Client").

THANKS & Cheers, Sebastian

**Comment by blacksenator** [comment]
Hallo Sebastian,
hast Du selbst herausgefunden welches PHP-Modul du nachladen musst?

**Comment by seal-82** [comment]
leider nein. Ich habe alle vorhandenen Module geladen. Die Fehlermeldung bezieht sich auf Soap. Das Modul ist aber geladen.

**Comment by blacksenator** [comment]
Ich habe ewig nicht an dem Coding geschraubt ... hast mit Composer alles geladen?

**Comment by seal-82** [comment]
das glaube ich dir. Composer hat keine schwerwiegenden Fehler ergeben. Allerdings verfolge ich jetzt einen anderen Ansatz. Auf Basis der PHP Scripte von folgender Seite: 
https://community.symcon.de/t/fritzbox-mit-soap-auslesen-und-steuern/35294/3
schreibe ich das XML Telefonbuch in eine Datei und formatiere sie dann mit Hilfe deiner XSL Templates. Wäre dann ein einfaches PHP Script. Melde mich wieder, wenn es läuft... Danke für deine Vorarbeit!
